# Generated by Django 4.2.4 on 2023-09-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='성함')),
                ('phoneNumber', models.CharField(max_length=128, verbose_name='전화번호 뒷자리')),
                ('inviterName', models.CharField(max_length=128, verbose_name='초대자이름')),
                ('complete', models.CharField(max_length=128)),
            ],
        ),
    ]
